### PR TITLE
Linter

### PR DESCRIPTION
**Pull request by max-ostapenko**
I went with default superlinter setup.

Had to switch off two tasks:
```
VALIDATE_JAVASCRIPT_PRETTIER: false
VALIDATE_MARKDOWN_PRETTIER: false
```
because of the conflicts:
- markdown and json didn't conform to 2 spaces indentation regardless of .editorconfig presence (maybe I missed something)

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
LGTM

Is it work adding `npm run lint` commands to allow this to be run offline? At least for the common ones like `eslint`, `markdownlint`...etc? Would save you having to wait for a github action to complete just to realise you've missed one small thing.

**Comment by max-ostapenko** [comment]
`standard` and `markdownlint` help to format and lint `js` and `md` locally.

**Comment by tunetheweb** [comment]
IIRC standard is very opinionated and deliberately doesn’t allow config (which might be why it didn’t play well with prettier?) Whereas eslint is more configurable. But maybe for this simple use case it doesn’t matter? So happy to merge this and can improve if future if we wanna.

**Comment by max-ostapenko** [comment]
Agree, it was just the fastest setup to get all checks green.
And I relied on my positive experience with `black`.

I'm not familiar with how well `standard` is maintained.
`eslint` may be a better choice for more granular preferences, but also could take hours to configure. It lost a lot of rules and formatting functionality to plugins in v9...

My issue with prettier - it created 3 space indents in markdown sublists.

**Pull request merged**
